version: '3.9'

services:
  schoolbook:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis: 
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${NAMEDB}
      POSTGRES_USER: ${DBLOGIN}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
volumes:
  redis:
    driver: local
  docker-nest-postgres:
